from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from database import engine, get_db
import models, schemas

# 1. Create the Database Tables automatically
models.Base.metadata.create_all(bind=engine)

app = FastAPI()

# --- API ENDPOINTS ---

@app.post("/users/", response_model=schemas.UserResponse)
def create_user(user: schemas.UserCreate, db: Session = Depends(get_db)):
    # Check if user already exists
    existing_user = db.query(models.User).filter(models.User.username == user.username).first()
    if existing_user:
        raise HTTPException(status_code=400, detail="Username already registered")
    
    # Create new user
    new_user = models.User(username=user.username, balance=user.initial_balance)
    db.add(new_user)
    db.commit()      # Save to DB
    db.refresh(new_user) # Get the ID generated by the DB
    return new_user

@app.get("/users/{user_id}", response_model=schemas.UserResponse)
def read_user(user_id: int, db: Session = Depends(get_db)):
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if user is None:
        raise HTTPException(status_code=404, detail="User not found")
    return user 

@app.post("/transactions/", response_model=schemas.TransactionResponse)
def transfer_funds(transaction: schemas.TransactionCreate, db: Session = Depends(get_db)):
    # 1. Get Sender and Recipient (WITH LOCKING)
    # .with_for_update() locks these rows. No other request can modify them 
    # until this request finishes.
    sender = db.query(models.User).filter(models.User.id == transaction.sender_id).with_for_update().first()
    recipient = db.query(models.User).filter(models.User.id == transaction.receiver_id).with_for_update().first()

    # 2. Basic Validations
    if not sender:
        raise HTTPException(status_code=404, detail="Sender not found")
    if not recipient:
        raise HTTPException(status_code=404, detail="Recipient not found")
    if sender.balance < transaction.amount:
        raise HTTPException(status_code=400, detail="Insufficient funds")

    # 3. Perform the Transfer
    sender.balance -= transaction.amount
    recipient.balance += transaction.amount

    # 4. Save the Transaction Record
    new_txn = models.Transaction(
        sender_id=transaction.sender_id,
        receiver_id=transaction.receiver_id,
        amount=transaction.amount,
        idempotency_key=transaction.idempotency_key
    )
    db.add(new_txn)

    # 5. Commit everything atomically (WITH IDEMPOTENCY CHECK)
    try:
        db.commit()
        db.refresh(new_txn)
    except IntegrityError:
        db.rollback() 
        # Return the original receipt if we find a duplicate key
        existing_txn = db.query(models.Transaction).filter(
            models.Transaction.idempotency_key == transaction.idempotency_key
        ).first()
        return existing_txn

    return new_txn
